server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EgusquizaOreJesus/configurations_server_proyectoCloud
  application:
    name: config-server


