server:
  port: 8888

spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Migue1Avalos/configurations_server_proyectoCloud.git
          clone-on-start: true



