# aqui haremos las peticiones
server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:    # rutas a las que se puede acceder

  config:
    import: optional:configserver:http://localhost:8888