spring:
  application:
    name: msvc-usuarios
  config:
    import: optional:configserver:http://54.221.169.95:8888

microservicio:
  base-url: http://54.221.169.95:9092

frontend:
  base-url: http://localhost:7777



