spring:
  application:
    name: msvc-usuarios
  config:
    import: optional:configserver:http://54.89.174.3:8888

microservicio:
  base-url: http://54.89.174.3:9092

frontend:
  base-url: http://localhost:7777



