spring:
  application:
    name: msvc-usuarios
  config:
    import: optional:configserver:http://localhost:8888

microservicio:
  base-url: http://localhost:9092

frontend:
  base-url: http://localhost:7777



