spring:
  application:
    name: msvc-usuarios
  config:
    import: optional:configserver:http://3.87.248.168:8888

microservicio:
  base-url: http://3.87.248.168:9092

frontend:
  base-url: http://localhost:7777



