server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Migue1Avalos/configurations_server_proyectoCloud.git
  application:
    name: config-server


