server:
  port: 9090

spring:
  application:
    name: msvc-hilos
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    jpa:
      hibernate:
        ddl-auto: create-drop
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  #datasource:
   # driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://54.89.174.3:5432/msvc_proyectocloud
    #username: postgres
   # password: postgres
  #jpa:
   # hibernate:
    #  ddl-auto: create # para que se cree la tabla en la base de datos
    #database: postgresql
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: 3.87.248.168
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/