version: '3.8'
services:
  config-server:
    build:
      context: ./microservice.config
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - spring-cloud-network

  eureka-server:
    build:
      context: ./microservice.eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-network

  gateway:
    build:
      context: ./microservice.gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network

  msvc-usuarios:
    build:
      context: ./microservice-usuarios
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    networks:
      - spring-cloud-network

  msvc-estados:
    build:
      context: ./microservice-estados
      dockerfile: Dockerfile
    ports:
      - "9093:9093"
    networks:
      - spring-cloud-network

  msvc-respuestas:
    build:
      context: ./microservice-respuesta
      dockerfile: Dockerfile
    ports:
      - "9094:9094"
    networks:
      - spring-cloud-network

  msvc-hilos:
    build:
      context: ./microservice-hilos
      dockerfile: Dockerfile
    ports:
      - "9095:9095"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge